name: device_frame_plus
description: Flutter package provides mockups for common devices, allowing developers to preview and test their apps within simulated device frames.
repository: https://github.com/StorybookToolkit/device_frame_plus
version: 1.4.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
